# インサートモードに入ったら読み込む
[[plugins]]
repo      = 'Shougo/neocomplete.vim'
on_i      = 1


[[plugins]] # 補完
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = '''
  " <TAB> で補完を選択
  inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete() '''
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''
# unite.vim を読み込んだら一緒に読み込む

# html関連のファイルを開いたら読み込む
[[plugins]]
repo      = 'mattn/emmet-vim'
on_ft     = ['html','css']
on_i = 1
hook_source = '''
  let g:user_emmet_mode = 'i'
  let g:use_emmet_complete_tag = 1
  let g:user_emmet_settings = {
  \   'variables': {
  \     'lang': "ja"
  \   },
  \   'indentation': '    '
  \ }
'''



[[plugins]]
repo      = 'othree/html5.vim'
on_ft     = ['html']

[[plugins]]
repo      = 'hail2u/vim-css3-syntax'
on_ft     = ['css']

[[plugins]]
repo      = 'jelera/vim-javascript-syntax'
on_ft     = ['html','js']

# Haskellの編集時に読み込む
[[plugins]]
repo      = 'ujihisa/neco-ghc'
on_ft     = ['hs']
on_i      = 1

[[plugins]]
repo      = 'kana/vim-filetype-haskell'
on_ft     = ['hs']

[[plugins]]
repo      = 'eagletmt/ghcmod-vim'
on_ft     = ['hs']
on_i      = 1

