# インサートモードに入ったら読み込む
[[plugins]]
repo      = 'Shougo/neocomplete.vim'
on_i      = 1

[[plugins]]
repo      = 'Shougo/unite.vim'
on_i      = 1
# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo      = 'osyo-manga/unite-filetype'
on_source = ['unite.vim']

[[plugins]]
repo      = 'mattn/emmet-vim'
on_ft     = ['html','css']

[[plugins]]
repo      = 'othree/html5.vim'
on_ft     = ['html']

[[plugins]]
repo      = 'hail2u/vim-css3-syntax'
on_ft     = ['css']

[[plugins]]
repo      = 'jelera/vim-javascript-syntax'
on_ft     = ['html','js']

[[plugins]]
repo      = 'ujihisa/neco-ghc'
on_ft     = ['hs']

[[plugins]]
repo      = 'kana/vim-filetype-haskell'
on_ft     = ['hs']

[[plugins]]
repo      = 'eagletmt/ghcmod-vim'
on_ft     = ['hs']
